SN---<:SN:>
SuE---<:SuE:>
DEMOPOE_RN---<:DEMOPOE_RN:>
DEMOPOE_LANG---<:DEMOPOE_LANG:>
DEMOPOE_YEAR---<:DEMOPOE_YEAR:>
DEMOPOE_AU---<:DEMOPOE_AU:>
DEMOPOE_TITLE---<:DEMOPOE_TITLE:>
DEMOPOE_ABS---<:DEMOPOE_ABS:>
